from __future__ import annotations

# Domain vocabularies used by heuristic knowledge extraction and document cleanup.
# Keep these lists focused on architectural meaning rather than generic English.

RULE_MARKERS = (
    # English
    "must",
    "shall",
    "should",
    "must address",
    "required",
    "requirement",
    "requirements",
    "have to",
    "has to",
    "mandatory",
    "obligatory",
    "requisite",
    "compulsory",
    "binding",
    "ensure",
    "provide",
    "provides",
    "provided",
    "support",
    "implement",
    "define",
    "establish",
    "maintain",
    "validate",
    "verify",
    "enforce",
    "protect",
    "control",
    "monitor",
    "audit",
    "apply",
    "follow",
    "comply",
    "adherence",
    "standardized",
    "enable",
    "enables",
    "leverage",
    "leverages",
    "represent",
    "represents",
    "correspond",
    "corresponds",
    "classify",
    "classifies",
    "collect",
    "collects",
    "transcode",
    "expose",
    "exposes",
    "authenticate",
    "authenticates",
    "authorize",
    "authorizes",
    "handle",
    "handles",
    # Russian
    "должен",
    "должна",
    "должно",
    "должны",
    "обязан",
    "обязана",
    "обязано",
    "обязатель",
    "необходимо",
    "требуется",
    "требование",
    "требования",
    "следует",
    "обеспечивать",
    "обеспечивает",
    "обеспечено",
    "гарантировать",
    "выполнять",
    "поддерживать",
    "предоставлять",
    "формировать",
    "хранить",
    "вести",
    "контролировать",
    "проверять",
    "валидировать",
)

CONSTRAINT_MARKERS = (
    # English
    "constraint",
    "constraints",
    "limitation",
    "limitations",
    "limit",
    "limits",
    "quota",
    "quotas",
    "restriction",
    "restrictions",
    "cannot",
    "can not",
    "must not",
    "shall not",
    "should not",
    "not allowed",
    "not mandatory",
    "optional",
    "prohibited",
    "forbidden",
    "no more than",
    "no less than",
    "at least",
    "minimum",
    "maximum",
    "unsupported",
    "without restriction",
    "unless",
    "except",
    "doesn't have the right to",
    "doesn’t have the right to",
    "does not have the right to",
    "no right to",
    "not be modified",
    "not be revoked",
    # Russian
    "не может",
    "не должен",
    "не должна",
    "не должно",
    "не должны",
    "не допускается",
    "нельзя",
    "запрещено",
    "огранич",
    "только",
    "не более",
    "не менее",
    "минимальн",
    "максимальн",
    "допускается",
    "при условии",
    "за исключением",
    "без отдельного",
    "не реже",
)

INTEGRATION_MARKERS = (
    # APIs / protocols
    "api",
    "openapi",
    "rest",
    "grpc",
    "http",
    "https",
    "endpoint",
    "endpoints",
    "json",
    "xml",
    "rdf",
    "turtle",
    "webhook",
    "websocket",
    # Messaging / async / data exchange
    "kafka",
    "rabbitmq",
    "queue",
    "topic",
    "message",
    "messages",
    "event",
    "events",
    "sync",
    "synchronization",
    "asynchronous",
    "batch",
    "stream",
    "real-time",
    "data exchange",
    "data feeds",
    "data integration",
    "technology integration",
    "federation",
    "catalog federation",
    "interoperability requirements",
    # Enterprise integration
    "bss",
    "oss",
    "business support systems",
    "operations support systems",
    "soa",
    "service oriented architecture",
    "service oriented architectures",
    "integration",
    "integration principle",
    "integration principles",
    "interoperability",
    "interoperate",
    "interoperable",
    "interactions",
    "communication",
    "server-to-server",
    "directory synchronization",
    "azure ad connect",
    "active directory federation services",
    # Russian
    "интеграц",
    "api",
    "openapi",
    "json-контракт",
    "эндпоинт",
    "интерфейс",
    "синхронизац",
    "обмен данными",
    "очеред",
    "сообщен",
    "событ",
    "поток",
    "веб-интерфейс",
    "url-источник",
    "взаимодейств",
    "омниканаль",
)

TECH_MARKERS = (
    # Databases / storage
    "postgres",
    "postgresql",
    "mysql",
    "oracle",
    "mongodb",
    "redis",
    "dynamodb",
    "rds",
    "s3",
    "glue",
    "athena",
    "quicksight",
    # Backend / frontend
    "node.js",
    "nodejs",
    "express.js",
    "express",
    "fastapi",
    "react",
    "react.js",
    "redux",
    "frontend",
    "backend",
    # DevOps / infrastructure
    "docker",
    "kubernetes",
    "k8s",
    "container",
    "containers",
    "ecs",
    "eks",
    "fargate",
    "lambda",
    "ec2",
    "cloudformation",
    "nginx",
    "vpc",
    "route 53",
    "api gateway",
    "sqs",
    "microservice",
    "microservices",
    "microservice architecture",
    "service oriented architecture",
    "service oriented architectures",
    "soa",
    "bss",
    "oss",
    "business support system",
    "business support systems",
    "operations support system",
    "operations support systems",
    # Security / identity
    "tls",
    "ssl",
    "oauth",
    "oauth2",
    "sso",
    "ldap",
    "iam",
    "mfa",
    "rbac",
    "ipsec",
    "vpn",
    "zero trust",
    "zta",
    "active directory",
    "azure ad",
    # Monitoring / analytics
    "prometheus",
    "grafana",
    "alertmanager",
    "cloudwatch",
    "cloudtrail",
    "guardduty",
    "x-ray",
    # Architecture / standards
    "aws",
    "azure",
    "office 365",
    "sharepoint",
    "oda",
    "sid",
    "etom",
    "tm forum",
    "aws well-architected",
    "aws well-architected framework",
    "archimate",
    "togaf",
    "togaf adm",
    "zachman",
    "dmar",
    "dmra",
    "doddaf",
    "enterprise metamodel",
    # Hardware / encoding / AI
    "llm",
    "gpu",
    "cpu",
    "ssd",
    "utf-8",
    "vector index",
    "векторный индекс",
    "микросервис",
    "микросервисы",
    "микросервисная архитектура",
    "сервис-ориентированная архитектура",
)

RISK_MARKERS = (
    # English
    "risk",
    "risks",
    "risk management",
    "dependency",
    "dependencies",
    "assumption",
    "assumptions",
    "uncertainty",
    "threat",
    "threats",
    "vulnerability",
    "vulnerabilities",
    "failure",
    "failures",
    "fault",
    "outage",
    "incident",
    "error",
    "errors",
    "gap",
    "gaps",
    "gap analysis",
    "consolidated gaps",
    "overlap",
    "overlaps",
    "bottleneck",
    "breach",
    "loss",
    "latency",
    "degraded",
    "disruption",
    "compliance",
    "regulatory",
    "missing information",
    "incomplete",
    "underutilization",
    "over-provisioning",
    "technical debt",
    "single point of failure",
    "resilience",
    "recoverability",
    "disaster recovery",
    "reliability",
    "availability",
    "scalability",
    "maintainability",
    "total cost of ownership",
    "tco",
    "cost optimization",
    "operational efficiency",
    # Russian
    "риск",
    "риски",
    "управление рисками",
    "зависим",
    "допущен",
    "неопредел",
    "угроз",
    "уязвим",
    "отказ",
    "сбой",
    "инцидент",
    "проблем",
    "ошибк",
    "замечан",
    "потер",
    "недоступ",
    "неполный",
    "неполном",
    "наруш",
    "безвозврат",
    "невозможност",
    "устареван",
    "аппаратного сбоя",
    "технический долг",
    "единая точка отказа",
    "отказоустойчив",
    "восстановлен",
    "масштабируем",
    "сопровождаем",
    "стоимость владения",
    "операционная эффективность",
)

ARCHITECTURE_CONCEPT_MARKERS = (
    # Enterprise architecture / TOGAF core
    "enterprise architecture",
    "architecture development method",
    "adm",
    "togaf adm",
    "preliminary phase",
    "architecture repository",
    "architecture roadmap",
    "architecture vision",
    "architecture landscape",
    "architecture capability",
    "enterprise continuum",
    "architecture content framework",
    "enterprise metamodel",
    "building block",
    "building blocks",
    "architecture building block",
    "architecture building blocks",
    "solution building block",
    "solution building blocks",
    "abb",
    "sbb",
    "architecture principle",
    "architecture principles",
    "architecture principles catalog",
    "business capability",
    "business capabilities catalog",
    "business capability map",
    "capability map",
    "capability-based planning",
    "value stream",
    "value stream map",
    "value stream catalog",
    "value stream stages catalog",
    "value stream/capability matrix",
    "stakeholder",
    "stakeholder management",
    "concern",
    "target architecture",
    "baseline architecture",
    "transition architecture",
    "reference architecture",
    "reference model",
    "government reference model",
    "business architecture",
    "data architecture",
    "application architecture",
    "technology architecture",
    "information systems architectures",
    "opportunities and solutions",
    "migration planning",
    "implementation governance",
    "architecture change management",
    "requirements management",
    "architecture governance",
    "architecture board",
    "architecture compliance",
    "architecture contract",
    "governance log",
    "governance",
    "strategic alignment",
    "enterprise alignment",
    "architecture requirements specification",
    "architecture definition document",
    "statement of architecture work",
    "request for architecture work",
    "implementation and migration plan",
    "migration plan",
    "work package",
    "deliverable",
    "artifact",
    "catalog",
    "matrix",
    "diagram",
    "architecture view",
    "architecture viewpoint",
    "architecture description",
    "business scenario",
    "business transformation readiness",
    "readiness assessment",
    "implementation factor",
    "standards information base",
    "organization model for the ea team",
    "ea capability roadmap",
    # TOGAF diagram/catalog patterns
    "business footprint diagram",
    "application communication diagram",
    "data dissemination diagram",
    "environments and locations diagram",
    "platform decomposition diagram",
    "networked computing hardware diagram",
    "solution concept diagram",
    "benefits diagram",
    "project context diagram",
    "organization mapping",
    "information map",
    "capability/organization matrix",
    "strategy/capability matrix",
    # Security / data governance architecture
    "security architecture",
    "enterprise security architecture",
    "data governance",
    "data entity",
    "data component",
    "application component",
    "technology component",
    "service quality",
    # Digital business and operating model language
    "digital capability",
    "digital technology adoption",
    "omnichannel capability",
    "cross-functional capability",
    "digital business operations",
    "customer centricity",
    "continuous innovation",
    "strategy transformation",
    "business model innovation",
    "platform-based business model",
    "platform-based business models",
    "multi-sided",
    "agility",
    "lifecycle",
    # ArchiMate concepts
    "business process",
    "business service",
    "business object",
    "business role",
    "business actor",
    "business interface",
    "application service",
    "application interface",
    "data object",
    "technology service",
    "technology interface",
    "technology node",
    # TM Forum / SID / eTOM concepts
    "business process framework",
    "information framework",
    "party management",
    "party interaction management",
    "core commerce",
    "product catalog",
    "product catalog management",
    "product inventory",
    "product inventory management",
    "product offering",
    "product specification",
    "service specification",
    "catalog management",
    "channel management",
    "customer facing service",
    "resource facing service",
    "business interaction",
    "billing account",
    # Russian
    "корпоративная архитектура",
    "метод разработки архитектуры",
    "архитектурный репозиторий",
    "архитектурная дорожная карта",
    "архитектурное видение",
    "архитектурный ландшафт",
    "архитектурная способность",
    "архитектурный принцип",
    "архитектурные принципы",
    "архитектурное соответствие",
    "архитектурный контракт",
    "архитектурная спецификация требований",
    "описание архитектуры",
    "запрос на архитектурную работу",
    "план внедрения и миграции",
    "план миграции",
    "рабочий пакет",
    "представление архитектуры",
    "точка зрения архитектуры",
    "заинтересованная сторона",
    "управление заинтересованными сторонами",
    "бизнес-возможность",
    "карта возможностей",
    "поток ценности",
    "целевая архитектура",
    "целевой архитектуре",
    "базовая архитектура",
    "переходная архитектура",
    "референсная архитектура",
    "модель правительства",
    "архитектурное управление",
    "стратегическое соответствие",
    "цифровая возможность",
    "омниканальная возможность",
    "сквозная возможность",
    "цифровые бизнес-операции",
    "клиентоцентричность",
    "непрерывные инновации",
    "трансформация стратегии",
    "инновация бизнес-модели",
    "платформенная бизнес-модель",
    "гибкость",
    "жизненный цикл",
    "бизнес-процесс",
    "бизнес-сервис",
    "бизнес-объект",
    "бизнес-роль",
    "бизнес-интерфейс",
    "прикладной компонент",
    "прикладной сервис",
    "прикладной интерфейс",
    "объект данных",
    "сущность данных",
    "компонент данных",
    "технологический компонент",
    "технологический сервис",
    "технологический интерфейс",
    "технологический узел",
    "информационная модель",
    "управление данными",
    "архитектура безопасности",
    "корпоративная архитектура безопасности",
    "управление сторонами",
    "каталог продуктов",
    "управление каталогом продуктов",
    "инвентаризация продуктов",
    "продуктовое предложение",
    "спецификация продукта",
    "спецификация сервиса",
    "управление каналами",
    "клиентский сервис",
    "ресурсный сервис",
    "бизнес-взаимодействие",
    "биллинговый аккаунт",
)

PREFIX_MARKERS = (
    "обязатель",
    "огранич",
    "минимальн",
    "максимальн",
    "интеграц",
    "синхронизац",
    "очеред",
    "сообщен",
    "событ",
    "взаимодейств",
    "омниканаль",
    "микросервис",
    "зависим",
    "допущен",
    "неопредел",
    "угроз",
    "уязвим",
    "проблем",
    "ошибк",
    "замечан",
    "потер",
    "недоступ",
    "неполный",
    "неполном",
    "наруш",
    "безвозврат",
    "невозможност",
    "устареван",
    "отказоустойчив",
    "восстановлен",
    "масштабируем",
    "сопровождаем",
)

LEGAL_DISCLAIMER_MARKERS = {
    "legal disclaimer",
    "disclaimer",
    "confidential",
    "copyright",
    "all rights reserved",
    "evaluation copy",
    "not for redistribution",
    "no part of this document",
    "without prior written permission",
    "provided as is",
    "trademark",
    "liability",
    "permission",
    "license",
    "правовая информация",
    "отказ от ответственности",
    "конфиденциаль",
    "авторск",
    "все права защищены",
    "без предварительного письменного",
    "товарн",
    "ответственност",
}

DOMAIN_SIGNAL_MARKERS = {
    "architecture",
    "component",
    "service",
    "api",
    "requirement",
    "integration",
    "database",
    "deployment",
    "security requirement",
    "business process",
    "stakeholder",
    "capability",
    "governance",
    "viewpoint",
    "deliverable",
    "artifact",
    "архитект",
    "компонент",
    "сервис",
    "требован",
    "интеграц",
    "база данных",
    "безопасн",
    "процесс",
    "заинтересован",
    "способност",
    "управлен",
}
