/* eslint-disable */
// Generated by frontend/scripts/generate-openapi-types.mjs from frontend/openapi.json.
// Do not edit manually, except for the UI-only KnowledgeScope helpers below.

import type { components, paths, SuccessJson } from '../generated/openapi';

export type TaskStatus = string;
export type RunStatus = string;
export type SolutionStatus = string;
export type ProtocolStatus = string;
export type ProtocolSummaryStatus = string;
export type Severity = string;

export interface KnowledgeScopeVersionSnapshot {
  knowledge_version_id?: string | null;
  knowledge_base_id?: string | null;
  knowledge_base_code?: string | null;
  version_code?: string | null;
  status?: string | null;
  created_at?: string | null;
  activated_at?: string | null;
  source_scope?: string | null;
  source_count?: number | null;
  document_count?: number | null;
  basis_document_count?: number | null;
  missing_required_packages?: string[];
  basis_documents?: Array<Record<string, unknown>>;
}

export interface KnowledgeScopeDocumentSnapshot {
  mode?: string | null;
  document_count?: number | null;
  selected_document_ids?: string[];
  effective_document_ids?: string[];
  selected_documents?: Array<Record<string, unknown>>;
}

export interface KnowledgeScope {
  mandatory_version?: KnowledgeScopeVersionSnapshot | null;
  selected_user_version?: KnowledgeScopeVersionSnapshot | null;
  effective_version_ids: string[];
  selected_generation_version_id?: string | null;
  basis_documents?: Array<Record<string, unknown>>;
  document_scope?: KnowledgeScopeDocumentSnapshot | null;
  snapshot_hash?: string | null;
}

export type GenerationDispatch = SuccessJson<paths['/tasks/{task_id}/generation-runs']['post']>;

export type HealthDependency = components['schemas']['DependencyHealthResponse'];
export type ReadyState = components['schemas']['DependenciesResponse'];
export type TaskListItem = components['schemas']['TaskListItemResponse'];
export type SolutionRegistryItem = components['schemas']['SolutionRegistryItemResponse'];
export type VerificationProtocolRegistryItem = components['schemas']['VerificationProtocolRegistryItemResponse'];
export type ClarificationQuestionItem = components['schemas']['ClarificationQuestionItem'];
export type ClarificationAnswer = components['schemas']['ClarificationAnswerResponse'];
export type ClarificationRequest = components['schemas']['ClarificationRequestResponse'];
export type GenerationRunRef = components['schemas']['GenerationRunRefResponse'];
export type TaskSnapshot = components['schemas']['TaskSnapshotResponse'];
export type GenerationRun = components['schemas']['GenerationRunResponse'];
export type GenerationRunAccepted = components['schemas']['GenerationRunAcceptedResponse'];
export type GenerationClarificationRequired = components['schemas']['GenerationClarificationRequiredResponse'];
export type SolutionSectionSourceRef = components['schemas']['SolutionSectionSourceRefResponse'];
export type SolutionSection = components['schemas']['SolutionSectionResponse'];
export type SolutionSectionAssessment = components['schemas']['SolutionSectionAssessmentResponse'];
export type SolutionArchitectureEntity = components['schemas']['SolutionArchitectureEntityResponse'];
export type SolutionArchitectureRelation = components['schemas']['SolutionArchitectureRelationResponse'];
export type SolutionArchitectureModel = components['schemas']['SolutionArchitectureModelResponse'];
export type SolutionArchitectureModelEnvelope = components['schemas']['SolutionArchitectureModelEnvelope'];
export type SolutionComponentInterface = components['schemas']['SolutionComponentInterfaceResponse'];
export type SolutionComponent = components['schemas']['SolutionComponentResponse'];
export type SolutionIntegration = components['schemas']['SolutionIntegrationResponse'];
export type SolutionListItem = components['schemas']['SolutionListItemResponse'];
export type SolutionRisk = components['schemas']['SolutionRiskResponse'];
export type SolutionVerificationRunRef = components['schemas']['SolutionVerificationRunRefResponse'];
export type PublicationRevision = components['schemas']['PublicationRevisionResponse'];
export type SnapshotSummary = components['schemas']['SnapshotSummaryResponse'];
export type Solution = components['schemas']['SolutionResponse'];
export type RenderedSolution = components['schemas']['SolutionRenderedResponse'];
export type VerificationRun = components['schemas']['VerificationRunResponse'];
export type VerificationBasisDocument = components['schemas']['VerificationBasisDocumentResponse'];
export type VerificationFinding = components['schemas']['VerificationFindingResponse'];
export type VerificationProtocolViolation = components['schemas']['VerificationProtocolViolationResponse'];
export type VerificationProtocolViolationsEnvelope = components['schemas']['VerificationProtocolViolationsEnvelope'];
export type VerificationProtocol = components['schemas']['VerificationProtocolResponse'];
export type RenderedVerificationProtocol = components['schemas']['VerificationProtocolRenderedResponse'];
export type ActiveKnowledgeVersion = components['schemas']['app__schemas__mvp__KnowledgeVersionResponse'];
export type KnowledgeBase = components['schemas']['KnowledgeBaseResponse'];
export type KnowledgeBaseDocument = components['schemas']['KnowledgeBaseDocumentResponse'];
export type Source = components['schemas']['SourceResponse'];
export type SourceDocument = components['schemas']['SourceDocumentResponse'];
export type KnowledgeBundleImportResult = components['schemas']['KnowledgeBundleImportResponse'];
export type DocumentChunk = components['schemas']['DocumentChunkResponse'];
export type DocumentSnapshot = components['schemas']['DocumentSnapshotResponse'];
export type ExtractedKnowledgeItem = components['schemas']['ExtractedKnowledgeItemResponse'];
export type DocumentMemory = components['schemas']['DocumentMemoryResponse'];
export type KnowledgeNotification = components['schemas']['KnowledgeNotificationResponse'];
export type KnowledgeVersion = components['schemas']['app__schemas__knowledge__KnowledgeVersionResponse'];
export type KnowledgeUpdateRun = components['schemas']['KnowledgeUpdateRunResponse'];
export type OperationItem = components['schemas']['OperationJournalItemResponse'];
export type OperationStep = components['schemas']['OperationStepResponse'];
export type AuditEvent = components['schemas']['AuditEventResponse'];
export type OperationDetail = components['schemas']['OperationDetailResponse'];
export type OperationMetrics = components['schemas']['OperationMetricsResponse'];
export type SolutionSectionAssessmentsEnvelope = components['schemas']['SolutionSectionAssessmentsEnvelope'];
